# Generated by Django 3.2.15 on 2022-08-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mindmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('revisions', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sort_number', models.PositiveIntegerField()),
                ('mindmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='mindmaps.mindmap')),
            ],
            options={
                'unique_together': {('mindmap', 'sort_number')},
            },
        ),
        migrations.CreateModel(
            name='BranchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sort_number', models.PositiveIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_line', to='mindmaps.branch')),
            ],
            options={
                'unique_together': {('branch', 'sort_number')},
            },
        ),
    ]
