# Generated by Django 3.2.15 on 2022-09-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmap',
            name='image_link',
            field=models.TextField(default='default-change-it'),
            preserve_default=False,
        ),
    ]
